# Generated by Django 5.1.7 on 2025-04-25 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('square', models.FloatField(verbose_name='Площадь квартиры')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('price', models.FloatField(verbose_name='Стоимость объекта')),
                ('address', models.TextField(verbose_name='Адрес объекта')),
                ('metro', models.CharField(max_length=200, verbose_name='Метро')),
                ('text', models.TextField(verbose_name='Описание объекта')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
