# Generated by Django 5.1.7 on 2025-05-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
