# Generated by Django 5.1.7 on 2025-07-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='images',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=1, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
